version: '3'
services:
  selenium:
    image: selenium/standalone-chrome
    ports:
    - 4444:4444
    - 7900:7900
  legion:
    build:
      context: ./
      dockerfile: ./Dockerfile
    #environment:
    #  - OpenAI__ApiEndpoint=...
    depends_on:
      - selenium